eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    #instance-id: ${eureka.instance.hostname}:${server.port}
    instance-id: localhost:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #defaultZone: http://112.126.59.115:7001/eureka/
      defaultZone: http://localhost:7001/eureka/
