server:
  port: 3344
spring:
  application:
    name: leyou-config
  profiles:
    active: dev
  rabbitmq:
    host: 112.126.59.115
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/gitteejava/leyou.git
          username: 1378975974@qq.com
          password: 1378975974@Wxb
          search-paths: leyou-config/config/
          force-pull: true
      label: master
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://172.17.40.83:7001/eureka/
      #defaultZone: http://localhost:7001/eureka/
